### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by Leoz83** [thiagoabreu/10g#1]
On nokia 8110 I have just a white screen
![image](https://user-images.githubusercontent.com/2699516/70563891-64954980-1b8f-11ea-9da0-4c8071c6dd74.png)

**Comment by thiagoabreu** [comment]
Not yet. It is still pretty much a mock for what a contact list should look like.

But you shouldn't see that blank page. Have you run the build script?

Try run `npm install`, then `npm run build` (you'll need npm installed in your system) before send to your 8110.
